CREATE TABLE IF NOT EXISTS Films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR (50),
    description VARCHAR (200),
    releaseDate DATE,
    duration INTEGER,
    Mpa INTEGER
);

CREATE TABLE IF NOT EXISTS Users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100),
    login VARCHAR(50),
    name VARCHAR(50),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS Likes (
    userId INTEGER,
    filmId INTEGER,
    PRIMARY KEY (userId, filmId)
);

CREATE TABLE IF NOT EXISTS Mpa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(10)
);

CREATE TABLE IF NOT EXISTS Genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS FilmGenre (
    filmId INTEGER,
    genreId INTEGER,
    PRIMARY KEY (filmId, genreId)
);

CREATE TABLE IF NOT EXISTS Friends (
    userId INTEGER,
    friendId INTEGER,
    status BOOLEAN,
    PRIMARY KEY (userId, friendId)
);